### ISSUE TITLE
Handle guardians address connection

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#32]
Reports from Guardians.

When GUARDIAN connects TETRA to stake,
They always failed to step 3 (selecting guardians)

Failure is normal operation due to "guardian cannot delegate to himself" policy.
And calculation handle guardian's address properly.

But our tool says there is no rewards problem.
https://orbs-network.github.io/voting/ko/reward?address=0xcB6172196BbCf5b4cf9949D7f2e4Ee802EF2b81D

## Solution

1. Tetra: If connected account (address) is a guardian, disable selecting guardian in staking wizard.
2. Hedron: If input address is a guardian, do not give "NO REWARDS" warning.

**Comment by talkol** [comment]
I understand from Andrey that this issue was fixed, not sure how..

**Comment by Eddy-orbs** [comment]
@andr444 Can you address commit info regarding this issue?

**Comment by Eddy-orbs** [comment]
https://orbs-network.github.io/voting/reward?address=0xf7ae622C77D0580f02Bcb2f92380d61e3F6e466c

Hedron is not fixed yet.

**Comment by Eddy-orbs** [comment]
complaint from Julia(Japanese guardian)

![Screenshot_20200520-014330_Telegram](https://user-images.githubusercontent.com/56513320/82354362-aa5a1600-9a3b-11ea-9c29-183c20d22b51.jpg)
